# Generated by Django 2.1.2 on 2018-10-04 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=50)),
                ('imagem', models.ImageField(height_field=200, max_length=200, upload_to='categoria_photos', width_field=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.TipoCategoria'),
        ),
    ]
