# Generated by Django 2.1.2 on 2018-10-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagem',
            field=models.ImageField(max_length=200, upload_to='.categoria_photos'),
        ),
    ]
