# Generated by Django 2.1.2 on 2018-10-04 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historia.Historia')),
            ],
        ),
    ]
