# Generated by Django 2.1.2 on 2018-10-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='restricao_etaria',
            field=models.IntegerField(choices=[(0, 'LIVRE'), (3, 'INFANT'), (5, 'CHILD'), (10, 'YOUNG'), (13, 'TEEN'), (16, 'ADULT'), (18, 'FORIBEN')], verbose_name='Restrição de Idade'),
        ),
    ]
